from scripts.constants.crawler import DEFAULT_SAVE_PATH as DEFAULT_SAVE_PATH, HEADERS as HEADERS, URL as URL
from scripts.utils.logger import logger as logger

def get_music_platform(): ...
def invert_platform(platform: str = ...): ...
def download_music(url, title, author, *, path: str = ...): ...
def main(name: str = ..., platform: str = ..., *, path: str = ...) -> bool: ...
