class JSObject(dict):
    def __init__(self, *args, **kwargs) -> None: ...
    def __setitem__(self, key, value, *, from_setattr: bool = ...) -> None: ...
    def __setattr__(self, key, value, *, from_setitem: bool = ...) -> None: ...
    def __delitem__(self, key, *, from_delattr: bool = ...) -> None: ...
    def __delattr__(self, item, *, from_delitem: bool = ...) -> None: ...
    def copy(self): ...
